CREATE TABLE "FoodCharityOrganizations"(
    "FoodCharityOrganizationID" BIGINT NOT NULL PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
    "Type" VARCHAR(255) CHECK
        (
            "Type" IN(
                'FoodPantry',
                'FoodBank',
                'SoupKitchen'
            )
        ) NOT NULL,
        "Address" TEXT NOT NULL,
        "ContactEmail" VARCHAR(255) NOT NULL,
        "Country" VARCHAR(255) NOT NULL
);

CREATE TABLE "FoodBins"(
    "FoodBinID" BIGINT NOT NULL PRIMARY KEY,
    "FoodCharityOrganizationID" BIGINT NOT NULL,
    "MACAddress" VARCHAR(255) NOT NULL,
    "FoodWeight" FLOAT(53) NOT NULL,
    "Temperature" FLOAT(53) NOT NULL,
    "Humidity" FLOAT(53) NOT NULL,
    "FoodSpoiled" BOOLEAN NOT NULL,
    FOREIGN KEY("FoodCharityOrganizationID") REFERENCES "FoodCharityOrganizations"("FoodCharityOrganizationID")
);

-- INSERT INTO "FoodCharityOrganizations"("Name", "Type","Address", "ContactEmail","Country") VALUES('Santhosh','FoodPantry','Address', 'santhoshparamasivam78@gmail.com', 'India');

-- ALTER TABLE "FoodCharityOrganizations"
-- ALTER COLUMN "FoodCharityOrganizationID" 
-- ADD GENERATED BY DEFAULT AS IDENTITY (MINVALUE 1 START WITH 1 INCREMENT BY 1) 